apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
data:
  aws-accesss-key: YXdzX2FjY2Vzc19rZXlfaWQgPSBBS0lBWUVXWUo1VkdaUEVaTk5ZMwphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSAzczhnaWxvczlHNkprT2tzTUpCQjV3UXhtenFCakZSaksvaExlUXo0CnJlZ2lvbiA9IHVzLWVhc3QtMQpvdXRwdXQgPSBqc29u
type: Opaque