version: '3.5'
services:
  reverseproxy:
    build: 
      context: ./udagram-reverseproxy
    image: reverseproxy
  backend-user:
    build: 
      context: ./udagram-api-user
    image: udagram-api-user
  backend-feed:
    build: ./udagram-api-feed
    image: udagram-api-feed
  frontend:
    build: ./udagram-frontend
    image: udagram-frontend:local